### PR TITLE
Add osx-arm64 support

### PR DESCRIPTION
**Pull request by tschoonj**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tschoonj** [comment]
@conda-forge/r  Could this get a review please? Thanks!

**Comment by mfansler** [comment]
@conda-forge-admin please rerender

**Comment by mfansler** [comment]
I'm baffled how you got a rerender that added osx-arm64 *prior* to editing `conda-forge.yml`. Anyway, just asked for another rerender for good measure. In the future, it is preferred not to manually migrate; rather, follow [the documented procedure](https://conda-forge.org/docs/maintainer/knowledge_base/#apple-silicon-builds) so the migrator can track.

**Review by mfansler — APPROVED** [review]

**Comment by tschoonj** [comment]
Yeah the commit ordering here is not chronological :-)

I did indeed modify the `conda-forge.yml` first, but didn't commit that, before running `conda smithy rerender --commit`.

Thanks for merging this in !

**Pull request merged**
